
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';


export const LOADING_OFFERS_START = 'LOADING_OFFERS_START';
export const LOADING_OFFERS_SUCCESS = 'LOADING_OFFERS_SUCCESS';
export const LOADING_OFFERS_FAILURE = 'LOADING_OFFERS_FAILURE';

export const RESERVE_OFFER_START = 'RESERVE_OFFER_START';
export const RESERVE_OFFER_SUCCESS = 'RESERVE_OFFER_SUCCESS';
export const RESERVE_OFFER_FAILURE = 'RESERVE_OFFER_FAILURE';

export const SELECT_CURRENT_OFFER = 'SELECT_CURRENT_OFFER';
export const CLEAR_CURRENT_OFFER = 'CLEAR_CURRENT_OFFER';

export const SEARCH_FROM_DATE_CHANGE = 'SEARCH_FROM_DATE_CHANGE';
export const SEARCH_TO_DATE_CHANGE = 'SEARCH_TO_DATE_CHANGE';
export const SEARCH_CITY_CHANGE = 'SEARCH_CITY_CHANGE';

